services:
  - type: web
    name: jd-parser
    env: python
    plan: free
    branch: main
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: OPENROUTER_API_KEY
        sync: false
